version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres_data/ddl/01_init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./postgres_data/dml/02_load_data.sql:/docker-entrypoint-initdb.d/02_load_data.sql
      - ./postgres_data/dml/03_create_data_mart.sql:/docker-entrypoint-initdb.d/03_create_data_mart.sql

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    depends_on:
      - postgres
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse_data/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
